### ISSUE TITLE
org.slf4j missing

### ISSUE THREAD

**Issue by akash-vartak** [iAmeeth/CL1#1]
Perhaps this is something you used from the internet as an external archive for java, in which case please provide the same in the repo.
If not then please explain it's source and usage.

Thanks in advance!

**Comment by iAmeeth** [comment]
I suppose the code uses Weka jar files which you need to get from their site.

**Comment by akash-vartak** [comment]
I did "add External Jars" in Eclipse Mars2.0 but this error persists, there is something else being linked here....
